In [ ]:
import time
import numpy as np
import pandas as pd
import datetime as dt
import cufflinks as cf
from pylab import plt
cf.set_config_file(offline=True)
plt.style.use('seaborn')
%matplotlib inline

In [ ]:
import fxcmpy


In [ ]:
fxcmpy.__version__

In [ ]:
from fxcmpy import fxcmpy_tick_data_reader as tdr

In [ ]:
print(tdr.get_available_symbols())

In [ ]:
start = dt.datetime(2018, 3, 26)
stop = dt.datetime(2018, 3, 29)

In [ ]:
%time td = tdr('EURUSD', start, stop)

In [ ]:
type(td)

In [ ]:
td.get_raw_data().info()


In [ ]:
%time td.get_data().info()

In [ ]:
%time td.get_data().info()

In [ ]:
sub = td.get_data(start='2018-03-27 12:00:00', end='2018-03-27 16:00:00')

In [ ]:
sub.head()

In [ ]:
sub['Mid'] = sub.mean(axis=1)
sub['SMA'] = sub['Mid'].rolling(1000).mean()

In [ ]:
sub[['Mid', 'SMA']].iplot()

In [ ]:
from fxcmpy import fxcmpy_candles_data_reader as cdr

In [ ]:
print(cdr.get_available_symbols())

In [ ]:
start = dt.datetime(2018, 3, 1)
stop = dt.datetime(2018, 3, 25)

In [ ]:
period = 'H1'

In [ ]:
candles = cdr('EURUSD', start, stop, period)

In [ ]:
type(candles)

In [ ]:
data = candles.get_data()

In [ ]:
data.info()

In [ ]:
data.head()

In [ ]:
start = dt.datetime(2017, 1, 3)
stop = dt.datetime(2017, 12, 31)

In [ ]:
period = 'D1'
candles = cdr('EURUSD', start, stop, period)

In [ ]:
candles.get_data().info()

In [ ]:
sub = pd.DataFrame({'Mid': (candles.get_data()['BidClose'] + candles.get_data()['AskClose']) / 2},
                  index = candles.get_data().index)
sub['Returns'] = np.log(sub / sub.shift(1))
sub.head()

In [ ]:
sub.iplot(subplots=True)

In [ ]:
sub['Returns'].iplot(kind='histogram')

In [ ]:
data = candles.get_data()[['AskOpen', 'AskHigh', 'AskLow', 'AskClose']]
data.columns = ['open', 'high', 'low', 'close']
data.info()

In [ ]:
qf = cf.QuantFig(data, title='EUR/USD', legend='top',
                 name='EUR/USD', datalegend=False)

In [ ]:
qf.iplot()

In [ ]:
qf.add_bollinger_bands(periods=10, boll_std=2,
                       colors=['magenta', 'grey'], fill=True)
qf.data.update()

In [ ]:
qf.iplot()

In [ ]:
qf.add_rsi(periods=14, showbands=False)
qf.data.update()

In [ ]:
qf.iplot()

In [ ]:
period = 'H1'
candles = cdr('EURUSD', start, stop, period)


In [ ]:
candles.get_data().info()

In [ ]:
data = pd.DataFrame(candles.get_data()[['AskClose', 'BidClose']].mean(axis=1),
                    columns=['midclose'])

In [ ]:
data.info()

In [ ]:
data.tail()

In [ ]:
data.iplot()

In [ ]:
"Feature Prepreation"

In [ ]:
data['returns'] = np.log(data / data.shift(1))

In [ ]:
lags = 5
cols = []
for lag in range(1, lags + 1):
    col = 'lag_%s' % lag
    data[col] = data['returns'].shift(lag)
    cols.append(col)

In [ ]:
cols

In [ ]:
from pylab import plt
plt.style.use('seaborn')
%matplotlib inline

In [ ]:
data['direction'] = np.sign(data['returns'])


In [ ]:
data['direction'] = np.sign(data['returns'])
to_plot = ['midclose', 'returns', 'direction']
data[to_plot].iloc[:100].plot(figsize=(10, 6),
        subplots=True, style=['-', '-', 'ro'], title='EUR/USD');


In [ ]:
import datetime as dt
import numpy as np
import pandas as pd
import fxcm


In [ ]:
candles = api.get_candles('EUR/USD', period='m5',
                         start=dt.datetime(2018, 2, 7),
                          stop=dt.datetime(2018, 2, 9))

In [ ]:
instruments = api.get_instruments()
print(instruments)

In [ ]:
candles = api.get_candles('USD/JPY', period='D1', number=10)

In [ ]:
# 10 most recent days | daily
candles

In [ ]:
import cufflinks as cf  # Cufflinks
cf.set_config_file(offline=True)  # set the plotting mode to offline

In [ ]:
start = dt.datetime(2017, 1, 1)
end = dt.datetime(2018, 1, 1)

In [ ]:
candles = api.get_candles('USD/JPY', period='D1',
                         start=start, stop=end)

In [ ]:
candles['askclose'].iplot()

In [ ]:
# 50 most recent 1 minute bars
candles = api.get_candles('EUR/USD', period='m1', number=50)
candles.tail(10)

In [ ]:
data = candles[['askopen', 'askhigh', 'asklow', 'askclose']]
data.columns = ['open', 'high', 'low', 'close']
data.info()

In [ ]:
qf = cf.QuantFig(data, title='EUR/USD', legend='top',
                 name='EUR/USD', datalegend=False)

In [ ]:
qf.iplot()

In [1]:
import datetime as dt
import numpy as np
import pandas as pd
import fxcm
api = fxcm.fxcm(config_file='fxcm.cfg')

ServerError: FXCM Server reports an error: Unauthorized.

In [ ]:
#candles = api.get_candles('EUR/USD', period='m5',
#                         start=dt.datetime(2018, 3, 6),
#                          stop=dt.datetime(2018, 3, 9))

#Changed to USD/JPY
candles = api.get_candles('EUR/USD', period='m5',
                         start=dt.datetime(2018, 3, 5),
                          stop=dt.datetime(2018, 3, 9))



In [ ]:
data = pd.DataFrame(candles[['askclose', 'bidclose']].mean(axis=1),
                    columns=['midclose'])

In [ ]:
data.head()

In [ ]:
data.tail()

In [ ]:
import cufflinks as cf  # Cufflinks
cf.set_config_file(offline=True)  # set the plotting mode to offline
data.iplot()

In [184]:
data['returns'] = np.log(data / data.shift(1))

In [185]:
lags = 3
cols = []
for lag in range(1, lags + 1):
    col = 'lag_%s' % lag
    data[col] = data['returns'].shift(lag)
    cols.append(col)

In [186]:
col = 'momentum'
data[col] = data['returns'].rolling(5).mean().shift(1)
cols.append(col)

In [187]:
cols

['lag_1', 'lag_2', 'lag_3', 'momentum']

In [188]:
from pylab import plt
plt.style.use('seaborn')
%matplotlib inline

In [189]:
data['direction'] = np.sign(data['returns'])
to_plot = ['midclose', 'returns', 'direction']
#data[to_plot].iloc[:100].plot(figsize=(10, 6),subplots=True, style=['-', '-', 'ro'], title='EUR/USD');

In [190]:
# the "patterns" = 2 ** lags
np.digitize(data[cols], bins=[0])[:10]

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 1, 1, 1]])

In [191]:
2 ** len(cols)

16

In [192]:
data.dropna(inplace=True)

In [193]:
from sklearn import svm

In [194]:
model = svm.SVC(C=100)

In [195]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1147 entries, 2018-03-05 00:30:00 to 2018-03-09 00:00:00
Data columns (total 7 columns):
midclose     1147 non-null float64
returns      1147 non-null float64
lag_1        1147 non-null float64
lag_2        1147 non-null float64
lag_3        1147 non-null float64
momentum     1147 non-null float64
direction    1147 non-null float64
dtypes: float64(7)
memory usage: 71.7 KB


In [196]:
%time model.fit(np.sign(data[cols]), np.sign(data['returns']))

CPU times: user 37.8 ms, sys: 2.36 ms, total: 40.2 ms
Wall time: 38.5 ms


SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [197]:
pred = model.predict(np.sign(data[cols]))
pred[:15]

array([ 1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,
        1., -1.])

In [198]:
data['position'] = pred

In [199]:
data['strategy'] = data['position'] * data['returns']

In [200]:
# unleveraged | no bid-ask spread or transaction costs | only in-sample
data[['returns', 'strategy']].cumsum().apply(np.exp).iplot()

In [201]:
data['position'].value_counts()

 1.0    621
-1.0    525
 0.0      1
Name: position, dtype: int64

In [202]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [203]:
mu = data['returns'].mean()
v = data['returns'].std()
bins = [mu - v, mu, mu + v]
train_x, test_x, train_y, test_y = train_test_split(
    data[cols].apply(lambda x: np.digitize(x, bins=bins)),                   
    np.sign(data['returns']),
    test_size=0.50, random_state=111)

In [204]:
train_x.sort_index(inplace=True)
train_y.sort_index(inplace=True)
test_x.sort_index(inplace=True)
test_y.sort_index(inplace=True)

In [205]:
# the patterns = buckets ** lags
train_x.head(5)

lag_1  lag_2  lag_3  momentum
date                                              
2018-03-05 00:40:00      3      2      2         2
2018-03-05 00:45:00      1      3      2         2
2018-03-05 00:50:00      2      1      3         2
2018-03-05 01:10:00      3      0      2         1
2018-03-05 01:15:00      2      3      0         1

In [206]:
test_x.head(5)

lag_1  lag_2  lag_3  momentum
date                                              
2018-03-05 00:30:00      2      1      2         2
2018-03-05 00:35:00      2      2      1         2
2018-03-05 00:55:00      0      2      1         2
2018-03-05 01:00:00      2      0      2         2
2018-03-05 01:05:00      0      2      0         1

In [207]:
4 ** len(cols)

256

In [208]:
#ax = data['midclose'][train_x.index].plot(style=['b.'], figsize=(10, 6))
#data['midclose'][test_x.index].plot(style=['r.'], ax=ax)
#data['midclose'].plot(ax=ax, lw=0.5, style=['k--']);

In [209]:
#ax = data['midclose'].iloc[-100:][train_x.index].plot(style=['bo'], figsize=(10, 6))
#data['midclose'].iloc[-100:][test_x.index].plot(style=['ro'], ax=ax)
#data['midclose'].iloc[-100:].plot(ax=ax, lw=0.5, style=['k--']);

In [210]:
model.fit(train_x, train_y)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [211]:
train_pred = model.predict(train_x)

In [212]:
accuracy_score(train_y, train_pred)

0.63176265270506105

In [213]:
test_pred = model.predict(test_x)

In [214]:
accuracy_score(test_y, test_pred)

0.50174216027874563

In [215]:
pred = model.predict(np.digitize(data[cols], bins=bins))
pred[:15]

array([ 1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,
        1.,  1.])

In [216]:
data['position'] = pred

In [217]:
data['strategy'] = data['position'] * data['returns']

In [218]:
# in-sample | unleveraged | no bid-ask spread or transaction costs
data.loc[train_x.index][['returns', 'strategy']].cumsum().apply(np.exp).iplot()

In [219]:
# out-of-sample | unleveraged | no bid-ask spread or transaction costs
data.loc[test_x.index][['returns', 'strategy']].cumsum().apply(np.exp).iplot()

In [220]:
# number of trades
sum(data['position'].diff() != 0)

489

In [221]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [222]:
nos = 50
mu = data['returns'].rolling(nos).mean()
v = data['returns'].rolling(nos).std()
def digits(s):
    r = np.where(s < mu - v, 0, np.nan)
    r = np.where(s > mu - v, 1, r)
    r = np.where(s > mu, 2, r)
    r = np.where(s > mu + v, 3, r)
    return r  

In [223]:
data[cols].apply(digits)
bins = [mu - v, mu, mu + v]
train_x, test_x, train_y, test_y = train_test_split(
    data[cols].apply(digits).dropna(),                   
    np.sign(data['returns']).iloc[nos-1:],
    test_size=0.50, random_state=111)


####### Changed from 0.5 -> 0.4
#data[cols].apply(digits)
#bins = [mu - v, mu, mu + v]
#train_x, test_x, train_y, test_y = train_test_split(
#    data[cols].apply(digits).dropna(),                   
#    np.sign(data['returns']).iloc[nos-1:],
#    test_size=0.50, random_state=111)


In [224]:
train_x.sort_index(inplace=True)
train_y.sort_index(inplace=True)
test_x.sort_index(inplace=True)
test_y.sort_index(inplace=True)

In [225]:
# the patterns = buckets ** lags
train_x.head(5)

lag_1  lag_2  lag_3  momentum
date                                              
2018-03-05 04:45:00    3.0    1.0    3.0       2.0
2018-03-05 04:55:00    1.0    1.0    3.0       2.0
2018-03-05 05:15:00    2.0    1.0    3.0       2.0
2018-03-05 05:20:00    1.0    2.0    1.0       2.0
2018-03-05 05:45:00    0.0    1.0    2.0       1.0

In [226]:
test_x.tail(5)

lag_1  lag_2  lag_3  momentum
date                                              
2018-03-08 23:20:00    1.0    0.0    1.0       1.0
2018-03-08 23:30:00    1.0    1.0    1.0       1.0
2018-03-08 23:35:00    2.0    1.0    1.0       1.0
2018-03-08 23:40:00    0.0    2.0    1.0       1.0
2018-03-08 23:50:00    1.0    2.0    0.0       1.0

In [227]:
4 ** len(cols)

256

In [228]:
#ax = data['midclose'][train_x.index].plot(style=['b.'], figsize=(10, 6))
#data['midclose'][test_x.index].plot(style=['r.'], ax=ax)
#data['midclose'].plot(ax=ax, lw=0.5, style=['k--']);

In [229]:
#ax = data['midclose'].iloc[-100:][train_x.index].plot(style=['bo'], figsize=(10, 6))
#data['midclose'].iloc[-100:][test_x.index].plot(style=['ro'], ax=ax)
#data['midclose'].iloc[-100:].plot(ax=ax, lw=0.5, style=['k--']);

In [230]:
model.fit(train_x, train_y)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [231]:
train_pred = model.predict(train_x)

In [232]:
accuracy_score(train_y, train_pred)

0.64845173041894355

In [233]:
test_pred = model.predict(test_x)

In [234]:
accuracy_score(test_y, test_pred)

0.51366120218579236

In [235]:
pred = model.predict(data[cols].apply(digits).dropna())
pred[:15]

array([ 1.,  1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,
       -1., -1.])

In [236]:
data['position'] = 0.0
data['position'].iloc[nos-1:] = pred

In [237]:
data['strategy'] = data['position'] * data['returns']

In [238]:
# in-sample | unleveraged | no bid-ask spread or transaction costs
data.loc[train_x.index][['returns', 'strategy']].cumsum().apply(np.exp).iplot()

In [239]:
# out-of-sample | unleveraged | no bid-ask spread or transaction costs
data.loc[test_x.index][['returns', 'strategy']].cumsum().apply(np.exp).iplot()

In [240]:
# number of trades
sum(data['position'].diff() != 0)

512

In [241]:
# Heading 1
